blank_issues_enabled: false
contact_links:
  - name: Questions and discussions
    url: https://github.com/hybridly/hybridly/discussions
    about: Use GitHub discussions for message-board style questions and discussions.
