blank_issues_enabled: false
contact_links:
  - name: Questions and discussions
    url: https://discord.gg/uZ8eC7kRFV
    about: Join our Discord server to discuss ask questions and join discussions.
